const homes = [
  {
    _id: "1",
    address: "123 Main St",
    price: 250000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    type: "Single Family Home",
    image: "/images/house1.jpg",
  },
  {
    _id: "2",
    address: "456 Oak St",
    price: 350000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2200,
    type: "Modern Apartment",
    image: "/images/house2.jpg",
  },
  {
    _id: "3",
    address: "789 Pine St",
    price: 200000,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 1200,
    type: "Cozy Cottage",
    image: "/images/house1.jpg",
  },
  {
    _id: "4",
    address: "567 Maple Ave",
    price: 300000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 2000,
    type: "Rural Retreat",
    image: "/images/house1.jpg",
  },
  {
    _id: "5",
    address: "890 Cedar Blvd",
    price: 400000,
    bedrooms: 5,
    bathrooms: 4,
    sqft: 2800,
    type: "Luxury Mansion",
    image: "/images/house1.jpg",
  },
  {
    _id: "6",
    address: "111 Birch Ln",
    price: 180000,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 1000,
    type: "Quaint Bungalow",
    image: "/images/house1.jpg",
  },
];

export default homes;
